### ISSUE TITLE
[Feature Request] - Remove command message

### ISSUE THREAD

**Issue by brettsaunders21** [CraftoryStudios/DiscordBot#3]
When you type a command ?guide the original message you sent remains in chat.

If the command is successful it would be great to delete the user's command message to clean up the chat a little bit.

**Comment by zneeley** [comment]
This has been added with pull request #4 Added commands template, general comments and remove ?messages.

**Comment by TheBusyBiscuit** [comment]
@zneeley You can make your PR auto-close issues btw by including syntax like
* Resolves #3
* fixes #3
(etc...)

in your commits!
https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords
